### ISSUE TITLE
FTP -> AWS FTPS data connection

### ISSUE THREAD

**Issue by kdesjard** [Castaglia/proftpd-mod_proxy#190]
Trying to proxy FTP to FTPS (AWS Transfer) and control connection works, however, data channel does not.  I think it may have to do with negotiating a new TLS session on the data channel.
```
2021-02-25 11:24:22,032 mod_proxy/0.8[206097]: [tls.msg] sent protocol record message (content_type = ApplicationData, len = 30)
2021-02-25 11:24:22,072 mod_proxy/0.8[206097]: [tls.msg] received protocol record message (content_type = ApplicationData, len = 71)
2021-02-25 11:24:22,072 mod_proxy/0.8[206097]: Entering Passive Mode (X,X,X,X,161,125).
2021-02-25 11:24:22,073 mod_proxy/0.8[206097]: [tls.msg] sent protocol record message (content_type = ApplicationData, len = 30)
2021-02-25 11:24:22,082 mod_proxy/0.8[206097]: starting TLS negotiation on data connection
2021-02-25 11:24:22,082 mod_proxy/0.8[206097]: [tls.info] (unknown): before SSL initialization
2021-02-25 11:24:22,082 mod_proxy/0.8[206097]: [tls.info] connecting: before SSL initialization
2021-02-25 11:24:22,082 mod_proxy/0.8[206097]: [tls.msg] sent protocol record message (content_type = Handshake, len = 512)
2021-02-25 11:24:22,082 mod_proxy/0.8[206097]: [tls.msg] sent TLSv1.2 'ClientHello' Handshake message (512 bytes)
...
2021-02-25 11:24:22,083 mod_proxy/0.8[206097]: [tls.info] connecting: SSLv3/TLS write client hello
2021-02-25 11:24:22,083 mod_proxy/0.8[206097]: [tls.info] connecting: SSLv3/TLS write client hello
2021-02-25 11:24:22,111 mod_proxy/0.8[206097]: [tls.info] connecting: SSLv3/TLS write client hello
2021-02-25 11:24:22,111 mod_proxy/0.8[206097]: unable to connect using TLS: system call error: [2] No such file or directory
2021-02-25 11:24:22,111 mod_proxy/0.8[206097]: unable to open data connection to s-XXXXXXXXXXX.server.transfer.ca-central-1.amazonaws.com: TLS negotiation failed
2021-02-25 11:24:22,111 mod_proxy/0.8[206097]: postopen error for backend data connection output stream: Operation not permitted
2021-02-25 11:24:23,087 mod_proxy/0.8[206089]: [tls.msg] sent protocol record message (content_type = Alert, len = 26)
2021-02-25 11:24:23,087 mod_proxy/0.8[206089]: [tls.msg] sent TLSv1.2 warning 'close_notify' Alert message (2 bytes)
2021-02-25 11:24:23,087 mod_proxy/0.8[206089]: [tls.info] writing: SSL/TLS alert warning: close notify
```
AWS resets the connection:
```
11:24:22.073356 IP X.X.X.X.34139 > AWS.8197: Flags [S], seq 991262000, win 29200, options [mss 1460,sackOK,TS val 2653508550 ecr 0,nop,wscale 7], length 0
11:24:22.082466 IP AWS.8197 > X.X.X.X.34139: Flags [S.], seq 2698804571, ack 991262001, win 26847, options [mss 1362,sackOK,TS val 1115335478 ecr 2653508550,nop,wscale 7], length 0
11:24:22.082483 IP X.X.X.X.34139 > AWS.8197: Flags [.], ack 1, win 229, options [nop,nop,TS val 2653508559 ecr 1115335478], length 0
11:24:22.083020 IP X.X.X.X.34139 > AWS.8197: Flags [P.], seq 1:518, ack 1, win 229, options [nop,nop,TS val 2653508560 ecr 1115335478], length 517
11:24:22.090089 IP AWS.8197 > X.X.X.X.34139: Flags [.], ack 1, win 210, options [nop,nop,TS val 1115335486 ecr 2653508559], length 0
11:24:22.091276 IP AWS.8197 > X.X.X.X.34139: Flags [.], ack 518, win 219, options [nop,nop,TS val 1115335487 ecr 2653508560], length 0
11:24:22.111562 IP AWS.8197 > X.X.X.X.34139: Flags [R.], seq 1, ack 518, win 219, options [nop,nop,TS val 1115335508 ecr 2653508560], length 0
```

**Comment by Castaglia** [comment]
Can you provide the output from `proftpd -V`, please?  And your full `proftpd.conf`, including the `mod_proxy` configuration?

**Comment by kdesjard** [comment]
proftpd version info:

Compile-time Settings:
  Version: 1.3.8rc1 (git)
  Platform: LINUX [Linux 4.18.0-240.10.1.el8_3.x86_64 x86_64]
  Built: Wed Jan 27 2021 15:17:04 GMT
  Built With:
    configure  '--enable-openssl' '--with-modules=mod_proxy:mod_tls'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic
  LIBS:  -lssl -lcrypto -lssl -lcrypto  -lsqlite3 -lsupp -lcrypt -ldl  -pthread

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /usr/local/var/proftpd.pid
    Scoreboard File:
      /usr/local/var/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    - Controls support
    - curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    - NLS support
    + OpenSSL support (OpenSSL 1.1.1g FIPS  21 Apr 2020, FIPS enabled)
    - PCRE support
    - POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    - Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

conf:

ServerName                      "ProFTPD Default Installation"
ServerType                      standalone
DefaultServer                   off
LogFormat                       default "%h %l %u %t \"%r\" %s %b"
LogFormat           all     "%{iso8601} %P %h %u \"%r\" %s %b %{transfer-millisecs}"
DebugLevel  1
ExtendedLog /var/log/proftpd-all.log ALL all
SystemLog /var/log/proftpd.log
Port                            21
UseIPv6                         off
Umask                           022
MaxInstances                    30
User                            nobody
Group                           nobody
DefaultRoot ~
AllowOverwrite          on
<Limit SITE_CHMOD>
  DenyAll
</Limit>

<Class forward-proxy>
    From X.X.X.X
    ProxyForwardEnabled on
</Class>

ServerIdent                     off
WtmpLog                         off
ProxyDataTransferPolicy         passive
PassivePorts                    41001 41500

ProxyTables /var/proftpd/proxy
ProxyEngine                     on
ProxyLog                        /var/log/proftpd-proxy.log
ProxyRole                       forward
ProxyForwardMethod              user@host
ProxyForwardTo ^s\-XXXXXX\.server\.transfer\.ca\-central\-1\.amazonaws\.com\:21$ [NC]
ProxyTLSEngine auto
ProxyTLSCACertificateFile /etc/pki/tls/cert.pem
ProxyTLSCertificateFile /etc/pki/tls/private/proftpdCertificate.pem
ProxyTLSCertificateKeyFile /etc/pki/tls/private/proftpdServerkey.pem
ProxyTLSProtocol ALL -SSLv3 -TLSv1 -TLSv1.1
#ProxyTLSCipherSuite TLSv1.3 TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256
ProxyTLSOptions EnableDiags

ProxyTLSVerifyServer off
ProxyTLSTransferProtectionPolicy required

TraceLog /var/log/proxy-trace.log

<IfModule mod_tls.c>
  TLSLog /var/log/proftpd-tls.log
  TLSOptions EnableDiags
</IfModule>

</IfModule mod_proxy.c>
  ProxyLog /var/log/proftpd-proxy.log
  ProxyTLSOptions EnableDiags

  Trace \
    proxy:30 \
    proxy.conn:30 \
    proxy.ftp.conn:30 \
    proxy.ftp.ctrl:30 \
    proxy.ftp.data:30 \
    proxy.ftp.msg:30 \
    proxy.ftp.sess:30 \
    proxy.ftp.xfer:30 \
    proxy.inet:30 \
    proxy.netio:30 \
    proxy.reverse:30 \
    proxy.session:30 \
    proxy.tls:30 \
    proxy.uri:30 \
    tls:30
</IfModule>

**Comment by Castaglia** [comment]
Excellent, thank you.  The `ProxyTLSOptions EnableDiags` should be providing more details about the TLS handshake; in particular, I'm interested in see the specific details about the messages sent.  Does AWS close the connection after the ClientHello is sent, without even sending a ServerHello back?

Another bit of diagnostic information to see might be the output from this command:
```
$ openssl s_client -connect s-XXXXXXXXXXX.server.transfer.ca-central-1.amazonaws.com:21 -msg \
  -servername s-XXXXXXXXXXX.server.transfer.ca-central-1.amazonaws.com \
  -start_tls ftp
```
This should (in theory) try the same TLS handshake that `mod_proxy` is doing, and help us see more of what AWS is doing.

**Comment by kdesjard** [comment]
Stripped out certificates, keys etc:

>>> TLS 1.3, Handshake [length 0163], ClientHello
<<< ??? [length 0005]
<<< TLS 1.3, Handshake [length 0055], ServerHello
<<< TLS 1.2, Handshake [length 0981], Certificate
depth=2 C = US, O = "Entrust, Inc.", OU = See www.entrust.net/legal-terms, OU = "(c) 2012 Entrust, Inc. - for authorized use only", CN = Entrust Root Certification Authority - EC1
verify return:1
depth=1 C = US, O = "Entrust, Inc.", OU = See www.entrust.net/legal-terms, OU = "(c) 2016 Entrust, Inc. - for authorized use only", CN = Entrust Certification Authority - L1F
verify return:1
depth=0 C = CA, ST = X, L = X, O = X, CN = X
verify return:1
<<< TLS 1.2, Handshake [length 0094], ServerKeyExchange
<<< TLS 1.2, Handshake [length 0004], ServerHelloDone
>>> ??? [length 0005]
>>> TLS 1.2, Handshake [length 0046], ClientKeyExchange
>>> ??? [length 0005]
>>> TLS 1.2, ChangeCipherSpec [length 0001]
>>> ??? [length 0005]
>>> TLS 1.2, Handshake [length 0010], Finished
<<< ??? [length 0005]
<<< ??? [length 0005]
<<< TLS 1.2, Handshake [length 0010], Finished
Certificate chain
Server certificate
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2808 bytes and written 496 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-ECDSA-AES256-GCM-SHA384
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES256-GCM-SHA384
    Session-ID: XXX
    Session-ID-ctx:
    Master-Key: XXX
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1614550086
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
220 Service ready for new user.
USER test
331 User name okay, need password for testftpsproxy.
PASS XXXXX
230 User logged in, proceed.
227 Entering Passive Mode (X,X,X,X,32,0)
LIST
521 Data connection cannot be opened with this PROT setting
PROT P
200 Command PROT okay.
PASV
227 Entering Passive Mode (X,X,X,X,32,2)
LIST
150 File status okay; about to open data connection.

**Comment by Castaglia** [comment]
Hmm, OK.  Thanks!  Nothing immediately standing out there.

I was hoping to see some details about how/why the TLS handshake, for a data transfer connection, was failing.  I may have to set up an AWS Transfer FTPS setup myself to see if I can reproduce this.

While I do that, I wanted to ask about these `mod_proxy` configurations you're using -- although I do not think they are related to the issue at hand:
```
ProxyTLSCACertificateFile /etc/pki/tls/cert.pem
ProxyTLSCertificateFile /etc/pki/tls/private/proftpdCertificate.pem
ProxyTLSCertificateKeyFile /etc/pki/tls/private/proftpdServerkey.pem
```

The `ProxyTLSCertificateFile` and `ProxyTLSCertificateKeyFile` directives are for configuring a _client_ cert/key, not a server cert/key -- for when the backend/destination FTPS server requires client auth; I don't think that is the case here, with AWS Transfers.

And I'm assuming the `/etc/pki/tls/cert.pem` trusted server CA bundle contains the necessary AWS CA certificates, otherwise the control connection's server certificate would not be verified properly -- although you _do_ use `ProxyTLSVerifyServer off`.

Would it be possible to use a configuration like the following, in your configuration -- and provide the log excerpts related to the failed `mod_proxy` data transfer?
```
ProxyLog /var/log/proxy.log
ProxyTLSOptions EnableDiags
TraceLog /var/log/proxy.log
Trace command:10 response:20 tls:30 proxy.tls:30
```
The goal with this is to have the normal `mod_proxy` logging, and the details TLS trace logging, both in the same file -- this helps to see the relevant order of operations.

**Comment by kdesjard** [comment]
Commented out the client cert stuff and here is the log:

2021-03-01 11:30:55,353 [210372] <response:1>: 220 X.X.X.X FTP server ready
2021-03-01 11:30:55,354 [210372] <response:9>: clearing response lists before dispatching command 'FEAT'
2021-03-01 11:30:55,354 [210372] <command:7>: dispatching PRE_CMD command 'FEAT' to mod_tls.c
2021-03-01 11:30:55,354 [210372] <command:7>: dispatching PRE_CMD command 'FEAT' to mod_core.c
2021-03-01 11:30:55,354 [210372] <command:7>: dispatching PRE_CMD command 'FEAT' to mod_core.c
2021-03-01 11:30:55,354 [210372] <command:7>: dispatching CMD command 'FEAT' to mod_proxy.c
2021-03-01 11:30:55,354 [210372] <command:7>: dispatching CMD command 'FEAT' to mod_core.c
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: 211 Features:
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) CLNT
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) EPRT
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) EPSV
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) HOST
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) MDTM
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) MFF modify;UNIX.group;UNIX.mode;
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) MFMT
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) RANG STREAM
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) REST STREAM
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) SIZE
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) TVFS
2021-03-01 11:30:55,354 [210372] <response:7>: response added to pending list: (null) End
2021-03-01 11:30:55,354 [210372] <command:7>: dispatching LOG_CMD command 'FEAT' to mod_log.c
2021-03-01 11:30:55,354 [210372] <response:9>: flushing response list for 'FEAT'
2021-03-01 11:30:55,354 [210372] <response:1>: 211-Features:
2021-03-01 11:30:55,354 [210372] <response:1>:  CLNT
2021-03-01 11:30:55,354 [210372] <response:1>:  EPRT
2021-03-01 11:30:55,354 [210372] <response:1>:  EPSV
2021-03-01 11:30:55,354 [210372] <response:1>:  HOST
2021-03-01 11:30:55,354 [210372] <response:1>:  MDTM
2021-03-01 11:30:55,354 [210372] <response:1>:  MFF modify;UNIX.group;UNIX.mode;
2021-03-01 11:30:55,354 [210372] <response:1>:  MFMT
2021-03-01 11:30:55,354 [210372] <response:1>:  MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;
2021-03-01 11:30:55,354 [210372] <response:1>:  RANG STREAM
2021-03-01 11:30:55,354 [210372] <response:1>:  REST STREAM
2021-03-01 11:30:55,354 [210372] <response:1>:  SIZE
2021-03-01 11:30:55,354 [210372] <response:1>:  TVFS
2021-03-01 11:30:55,354 [210372] <response:1>: 211 End
2021-03-01 11:30:55,355 [210372] <response:9>: clearing response lists before dispatching command 'CLNT'
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching PRE_CMD command 'CLNT lftp/4.3.7' to mod_tls.c
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching PRE_CMD command 'CLNT lftp/4.3.7' to mod_core.c
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching PRE_CMD command 'CLNT lftp/4.3.7' to mod_core.c
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching CMD command 'CLNT lftp/4.3.7' to mod_proxy.c
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching CMD command 'CLNT lftp/4.3.7' to mod_core.c
2021-03-01 11:30:55,355 [210372] <response:7>: response added to pending list: 200 OK
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching LOG_CMD command 'CLNT lftp/4.3.7' to mod_log.c
2021-03-01 11:30:55,355 [210372] <response:9>: flushing response list for 'CLNT'
2021-03-01 11:30:55,355 [210372] <response:1>: 200 OK
2021-03-01 11:30:55,355 [210372] <response:9>: clearing response lists before dispatching command 'HOST'
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching PRE_CMD command 'HOST X.X.X.X' to mod_tls.c
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching PRE_CMD command 'HOST X.X.X.X' to mod_core.c
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching PRE_CMD command 'HOST X.X.X.X' to mod_core.c
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching CMD command 'HOST X.X.X.X' to mod_proxy.c
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching CMD command 'HOST X.X.X.X' to mod_core.c
2021-03-01 11:30:55,355 [210372] <response:7>: response added to pending list: 220 HOST command successful
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching POST_CMD command 'HOST X.X.X.X' to mod_core.c
2021-03-01 11:30:55,355 [210372] <command:7>: dispatching LOG_CMD command 'HOST X.X.X.X' to mod_log.c
2021-03-01 11:30:55,355 [210372] <response:9>: flushing response list for 'HOST'
2021-03-01 11:30:55,355 [210372] <response:1>: 220 HOST command successful
2021-03-01 11:30:55,356 [210372] <response:9>: clearing response lists before dispatching command 'OPTS'
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching PRE_CMD command 'OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_tls.c
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching PRE_CMD command 'OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_core.c
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching PRE_CMD command 'OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_core.c
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching CMD command 'OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_proxy.c
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching CMD command 'OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_core.c
2021-03-01 11:30:55,356 [210372] <response:9>: clearing response lists before dispatching command 'OPTS_MLST'
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching PRE_CMD command 'OPTS_MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_tls.c
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching PRE_CMD command 'OPTS_MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_core.c
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching PRE_CMD command 'OPTS_MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_core.c
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching CMD command 'OPTS_MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_proxy.c
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching CMD command 'OPTS_MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_facts.c
2021-03-01 11:30:55,356 [210372] <response:7>: response added to pending list: 200 MLST OPTS modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching LOG_CMD command 'OPTS_MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_log.c
2021-03-01 11:30:55,356 [210372] <response:9>: flushing response list for 'OPTS_MLST'
2021-03-01 11:30:55,356 [210372] <response:1>: 200 MLST OPTS modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;
2021-03-01 11:30:55,356 [210372] <command:7>: dispatching LOG_CMD command 'OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner;' to mod_log.c
2021-03-01 11:30:55,356 [210372] <response:9>: flushing response list for 'OPTS'
2021-03-01 11:30:55,357 [210372] <response:9>: clearing response lists before dispatching command 'USER'
2021-03-01 11:30:55,357 [210372] <command:7>: dispatching PRE_CMD command 'USER testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com' to mod_tls.c
2021-03-01 11:30:55,357 [210372] <command:7>: dispatching PRE_CMD command 'USER testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com' to mod_core.c
2021-03-01 11:30:55,357 [210372] <command:7>: dispatching PRE_CMD command 'USER testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com' to mod_core.c
2021-03-01 11:30:55,357 [210372] <command:7>: dispatching PRE_CMD command 'USER testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com' to mod_delay.c
2021-03-01 11:30:55,357 [210372] <command:7>: dispatching PRE_CMD command 'USER testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com' to mod_auth.c
2021-03-01 11:30:55,357 [210372] <command:7>: dispatching CMD command 'USER testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com' to mod_proxy.c
2021-03-01 11:30:55,496 [210372] <proxy.tls:9>: sending SNI 's-XXXX.server.transfer.ca-central-1.amazonaws.com'
2021-03-01 11:30:55,496 [210372] <proxy.tls:9>: requesting stapled OCSP response
2021-03-01 11:30:55,496 [210372] <proxy.tls:19>: looking for cached SSL session using key 'ftp://s-XXXX.server.transfer.ca-central-1.amazonaws.com:21'
2021-03-01 11:30:55,496 [210372] <proxy.tls:12>: found cached SSL session using key 'ftp://s-XXXX.server.transfer.ca-central-1.amazonaws.com:21'
2021-03-01 11:30:55,496 [210372] <proxy.tls:27>: sent TLSv1.2 Handshake (512 bytes)
2021-03-01 11:30:55,496 [210372] <proxy.tls:17>: WANT_READ encountered while connecting on fd 14, waiting to read data
2021-03-01 11:30:55,509 [210372] <proxy.tls:27>: received TLSv1.2 Handshake (85 bytes)
2021-03-01 11:30:55,509 [210372] <proxy.tls:27>: received TLSv1.2 Handshake (2433 bytes)
2021-03-01 11:30:55,511 [210372] <proxy.tls:27>: received TLSv1.2 Handshake (149 bytes)
2021-03-01 11:30:55,512 [210372] <proxy.tls:27>: received TLSv1.2 Handshake (4 bytes)
2021-03-01 11:30:55,512 [210372] <proxy.tls:1>: stapled OCSP response:
2021-03-01 11:30:55,512 [210372] <proxy.tls:1>: OCSP response: no response sent
2021-03-01 11:30:55,512 [210372] <proxy.tls:27>: sent TLSv1.2 Handshake (70 bytes)
2021-03-01 11:30:55,512 [210372] <proxy.tls:27>: sent TLSv1.2 Handshake (16 bytes)
2021-03-01 11:30:55,512 [210372] <proxy.tls:17>: WANT_READ encountered while connecting on fd 14, waiting to read data
2021-03-01 11:30:55,523 [210372] <proxy.tls:17>: WANT_READ encountered while connecting on fd 14, waiting to read data
2021-03-01 11:30:55,574 [210372] <proxy.tls:27>: received TLSv1.2 Handshake (16 bytes)
2021-03-01 11:30:55,574 [210372] <proxy.tls:9>: negotiated NEW SSL/TLS session
2021-03-01 11:30:55,574 [210372] <proxy.tls:19>: caching SSL session using key 'ftp://s-XXXX.server.transfer.ca-central-1.amazonaws.com:21'
2021-03-01 11:30:55,575 [210372] <proxy.tls:19>: successfully cached SSL session using key 'ftp://s-XXXX.server.transfer.ca-central-1.amazonaws.com:21'
2021-03-01 11:30:55,587 [210372] <response:1>: 331 User name okay, need password for testftpsproxy.
2021-03-01 11:30:55,587 [210372] <response:7>: error response added to pending list: 500 USER: No such file or directory
2021-03-01 11:30:55,587 [210372] <command:7>: dispatching POST_CMD command 'USER testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com' to mod_delay.c
2021-03-01 11:30:55,587 [210372] <command:7>: dispatching LOG_CMD command 'USER testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com' to mod_log.c
2021-03-01 11:30:55,587 [210372] <command:7>: dispatching LOG_CMD command 'USER testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com' to mod_delay.c
2021-03-01 11:30:55,587 [210372] <response:9>: flushing response list for 'USER'
2021-03-01 11:30:55,587 [210372] <response:9>: clearing response lists before dispatching command 'PASS'
2021-03-01 11:30:55,587 [210372] <command:7>: dispatching PRE_CMD command 'PASS (hidden)' to mod_tls.c
2021-03-01 11:30:55,587 [210372] <command:7>: dispatching PRE_CMD command 'PASS (hidden)' to mod_core.c
2021-03-01 11:30:55,587 [210372] <command:7>: dispatching PRE_CMD command 'PASS (hidden)' to mod_core.c
2021-03-01 11:30:55,587 [210372] <command:7>: dispatching PRE_CMD command 'PASS (hidden)' to mod_delay.c
2021-03-01 11:30:55,587 [210372] <command:7>: dispatching PRE_CMD command 'PASS (hidden)' to mod_auth.c
2021-03-01 11:30:55,587 [210372] <command:7>: dispatching CMD command 'PASS (hidden)' to mod_proxy.c
2021-03-01 11:30:56,399 [210372] <response:1>: 230 User logged in, proceed.
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching POST_CMD command 'PASS (hidden)' to mod_tls.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching POST_CMD command 'PASS (hidden)' to mod_delay.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching POST_CMD command 'PASS (hidden)' to mod_log.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching POST_CMD command 'PASS (hidden)' to mod_ls.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching POST_CMD command 'PASS (hidden)' to mod_auth.c
2021-03-01 11:30:56,400 [210372] <response:7>: response added to pending list: 230 User testftpsproxy@s-XXXX.server.transfer.ca-central-1.amazonaws.com logged in
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching POST_CMD command 'PASS (hidden)' to mod_rlimit.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching POST_CMD command 'PASS (hidden)' to mod_xfer.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching POST_CMD command 'PASS (hidden)' to mod_core.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching LOG_CMD command 'PASS (hidden)' to mod_log.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching LOG_CMD command 'PASS (hidden)' to mod_delay.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching LOG_CMD command 'PASS (hidden)' to mod_auth.c
2021-03-01 11:30:56,400 [210372] <response:9>: flushing response list for 'PASS'
2021-03-01 11:30:56,400 [210372] <response:19>: responses blocked, not flushing response chain
2021-03-01 11:30:56,400 [210372] <response:9>: clearing response lists before dispatching command 'PWD'
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching PRE_CMD command 'PWD' to mod_tls.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching PRE_CMD command 'PWD' to mod_core.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching PRE_CMD command 'PWD' to mod_core.c
2021-03-01 11:30:56,400 [210372] <command:7>: dispatching CMD command 'PWD' to mod_proxy.c
2021-03-01 11:30:56,410 [210372] <response:1>: 257 "/testftpsbucket-2021-02-05" is current directory.
2021-03-01 11:30:56,410 [210372] <command:7>: dispatching LOG_CMD command 'PWD' to mod_log.c
2021-03-01 11:30:56,410 [210372] <response:9>: flushing response list for 'PWD'
2021-03-01 11:30:56,411 [210372] <response:9>: clearing response lists before dispatching command 'PASV'
2021-03-01 11:30:56,411 [210372] <command:7>: dispatching PRE_CMD command 'PASV' to mod_tls.c
2021-03-01 11:30:56,411 [210372] <command:7>: dispatching PRE_CMD command 'PASV' to mod_core.c
2021-03-01 11:30:56,411 [210372] <command:7>: dispatching PRE_CMD command 'PASV' to mod_core.c
2021-03-01 11:30:56,411 [210372] <command:7>: dispatching CMD command 'PASV' to mod_proxy.c
2021-03-01 11:30:56,447 [210372] <response:1>: 227 Entering Passive Mode (X.X.X.X,160,201).
2021-03-01 11:30:56,447 [210372] <command:7>: dispatching LOG_CMD command 'PASV' to mod_log.c
2021-03-01 11:30:56,447 [210372] <response:9>: flushing response list for 'PASV'
2021-03-01 11:30:56,448 [210372] <response:9>: clearing response lists before dispatching command 'LIST'
2021-03-01 11:30:56,448 [210372] <command:7>: dispatching PRE_CMD command 'LIST' to mod_tls.c
2021-03-01 11:30:56,448 [210372] <command:7>: dispatching PRE_CMD command 'LIST' to mod_core.c
2021-03-01 11:30:56,448 [210372] <command:7>: dispatching PRE_CMD command 'LIST' to mod_core.c
2021-03-01 11:30:56,448 [210372] <command:7>: dispatching CMD command 'LIST' to mod_proxy.c
2021-03-01 11:30:56,458 [210372] <proxy.tls:9>: sending SNI 's-XXXX.server.transfer.ca-central-1.amazonaws.com'
2021-03-01 11:30:56,458 [210372] <proxy.tls:9>: requesting stapled OCSP response
2021-03-01 11:30:56,458 [210372] <proxy.tls:27>: sent TLSv1.2 Handshake (512 bytes)
2021-03-01 11:30:56,459 [210372] <proxy.tls:17>: WANT_READ encountered while connecting on fd 18, waiting to read data
2021-03-01 11:30:56,488 [210372] <command:7>: dispatching LOG_CMD_ERR command 'LIST' to mod_log.c
2021-03-01 11:30:56,488 [210372] <command:7>: dispatching LOG_CMD_ERR command 'LIST' to mod_ls.c
2021-03-01 11:30:56,488 [210372] <response:9>: flushing error response list for 'LIST'
2021-03-01 11:36:01,451 [210372] <command:6>: client sent EOF, closing control connection
2021-03-01 11:36:01,451 [210372] <proxy.tls:27>: sent TLSv1.2 Alert (2 bytes)
2021-03-01 11:36:01,452 [210372] <proxy.tls:19>: caching SSL session using key 'ftp://s-XXXX.server.transfer.ca-central-1.amazonaws.com:21'
2021-03-01 11:36:01,453 [210372] <proxy.tls:19>: successfully cached SSL session using key 'ftp://s-XXXX.server.transfer.ca-central-1.amazonaws.com:21'
2021-03-01 11:36:01,453 [210372] <proxy.tls:17>: TLS session cleanly shut down

**Comment by kdesjard** [comment]
Not sure if this helps but I did a capture between the proxy host and AWS:

PROFTPD -> AWS 

Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 512
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 508
            Version: TLS 1.2 (0x0303)
            Random: 47202eab5f7e12565584155bf10627429fb75e7c9a697d5e…
            Session ID Length: 32
            Session ID: 0c601b8ab91a80987c60b7538472c085b222176be3552ec1…
            Cipher Suites Length: 56
            Cipher Suites (28 suites)
            Compression Methods Length: 1
            Compression Methods (1 method)
            Extensions Length: 379
            Extension: server_name (len=67)
            Extension: ec_point_formats (len=4)
            Extension: supported_groups (len=12)
            Extension: session_ticket (len=0)
            Extension: status_request (len=5)
            Extension: next_protocol_negotiation (len=0)
            Extension: application_layer_protocol_negotiation (len=6)
            Extension: encrypt_then_mac (len=0)
            Extension: extended_master_secret (len=0)
            Extension: signature_algorithms (len=38)
            Extension: padding (len=203)

            
AWS -> PROFTPD
            
TLSv1.2 Record Layer: Handshake Protocol: Multiple Handshake Messages
    Content Type: Handshake (22)
    Version: TLS 1.2 (0x0303)
    Length: 2670
    Handshake Protocol: Server Hello
        Handshake Type: Server Hello (2)
        Length: 81
        Version: TLS 1.2 (0x0303)
        Random: 46250abe0063c92031796e85e61bdcd29a3b1e23772cf673…
        Session ID Length: 32
        Session ID: 7d8acab2dd3ec410abe15377a8999fe5f3d8a1eb23a49273…
        Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
        Compression Method: null (0)
        Extensions Length: 9
        Extension: extended_master_secret (len=0)
        Extension: renegotiation_info (len=1)
    Handshake Protocol: Certificate
        Handshake Type: Certificate (11)
        Length: 2429
        Certificates Length: 2426
        Certificates (2426 bytes)
    Handshake Protocol: Server Key Exchange
        Handshake Type: Server Key Exchange (12)
        Length: 144
        EC Diffie-Hellman Server Params
    Handshake Protocol: Server Hello Done
        Handshake Type: Server Hello Done (14)
        Length: 0


PROFTPD -> AWS            

TLSv1.2 Record Layer: Handshake Protocol: Client Key Exchange
    Content Type: Handshake (22)
    Version: TLS 1.2 (0x0303)
    Length: 70
    Handshake Protocol: Client Key Exchange
        Handshake Type: Client Key Exchange (16)
        Length: 66
        EC Diffie-Hellman Client Params

    
AWS -> PROFTPD

TLSv1.2 Record Layer: Change Cipher Spec Protocol: Change Cipher Spec
    Content Type: Change Cipher Spec (20)
    Version: TLS 1.2 (0x0303)
    Length: 1
    Change Cipher Spec Message

AWS -> PROFTPD    

TLSv1.2 Record Layer: Handshake Protocol: Encrypted Handshake Message
    Content Type: Handshake (22)
    Version: TLS 1.2 (0x0303)
    Length: 40
    Handshake Protocol: Encrypted Handshake Message


        
Passive Data Connection:

PROFTPD -> AWS

Transport Layer Security
    TLSv1 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 512
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 508
            Version: TLS 1.2 (0x0303)
            Random: 3a2f2a855d2c22f6adbc8bd846f5d4c87eb5277d3847a341…
            Session ID Length: 32
            Session ID: 7d8acab2dd3ec410abe15377a8999fe5f3d8a1eb23a49273…
            Cipher Suites Length: 56
            Cipher Suites (28 suites)
            Compression Methods Length: 1
            Compression Methods (1 method)
            Extensions Length: 379
            Extension: server_name (len=67)
            Extension: ec_point_formats (len=4)
            Extension: supported_groups (len=12)
            Extension: session_ticket (len=0)
            Extension: status_request (len=5)
            Extension: next_protocol_negotiation (len=0)
            Extension: application_layer_protocol_negotiation (len=6)
            Extension: encrypt_then_mac (len=0)
            Extension: extended_master_secret (len=0)
            Extension: signature_algorithms (len=38)
            Extension: padding (len=203)

            
AWS Resets data conn

**Comment by Castaglia** [comment]
Hmm.  In this [AWS Transfer Family doc](https://docs.aws.amazon.com/transfer/latest/userguide/transfer-file.html), it mentions:
> For FTP and FTPS, TLS - PROT C (unprotected) TLS for the data connection is the default.

By default, `mod_proxy` wants to require TLS for backend data transfer connections.  So, given the above docs, you might try adding this to your `mod_proxy` configuration:
```
# Disable TLS for backend data transfers
ProxyTLSTransferProtectionPolicy clear
```

**Comment by kdesjard** [comment]
FEAT
530 Access denied.

I changed the ProxyTLSTransferProtectionPolicy to clear, restarted proftpd and it's still trying to establish a TLS session (see below). I'm not sure if I'm missing something.   I've put the proxy setup within a virtualhost:

<VirtualHost X.X.X.X>
        ServerIdent                     off
        WtmpLog                         off
        PassivePorts                    41001 41500
        ProxyEngine                     on
        ProxyLog                        /var/log/proftpd-proxy.log
        ProxyRole                       forward
        ProxyDataTransferPolicy         passive
        ProxyForwardMethod              user@host
        ProxyForwardTo ^s\-XXXXXXX\.server\.transfer\.ca\-central\-1\.amazonaws\.com\:21$ [NC]
        ProxyTLSEngine auto
        ProxyTLSCACertificateFile /etc/pki/tls/cert.pem
        #ProxyTLSCertificateFile /etc/pki/tls/private/proftpdCertificate.pem
        #ProxyTLSCertificateKeyFile /etc/pki/tls/private/proftpdServerkey.pem
        ProxyTLSProtocol ALL -SSLv3 -TLSv1 -TLSv1.1
        #ProxyTLSCipherSuite TLSv1.3 TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256
        ProxyTLSOptions EnableDiags
        ProxyTLSVerifyServer off
        ProxyTLSOptions EnableDiags
        ProxyTLSTransferProtectionPolicy clear
</VirtualHost>


2021-03-11 16:03:58,576 mod_proxy/0.8[282494]: Entering Passive Mode (X,X,X,X,161,230).
2021-03-11 16:03:58,577 mod_proxy/0.8[282494]: [tls.msg] sent protocol record message (content_type = ApplicationData, len = 30)
**2021-03-11 16:03:58,587 mod_proxy/0.8[282494]: starting TLS negotiation on data connection**
2021-03-11 16:03:58,587 mod_proxy/0.8[282494]: [tls.info] (unknown): before SSL initialization
2021-03-11 16:03:58,587 mod_proxy/0.8[282494]: [tls.info] connecting: before SSL initialization
2021-03-11 16:03:58,587 mod_proxy/0.8[282494]: [tls.msg] sent protocol record message (content_type = Handshake, len = 512)
2021-03-11 16:03:58,587 mod_proxy/0.8[282494]: [tls.msg] sent TLSv1.2 'ClientHello' Handshake message (512 bytes)
2021-03-11 16:03:58,587 mod_proxy/0.8[282494]: [tls.info] connecting: SSLv3/TLS write client hello
2021-03-11 16:03:58,587 mod_proxy/0.8[282494]: [tls.info] connecting: SSLv3/TLS write client hello
2021-03-11 16:03:58,628 mod_proxy/0.8[282494]: [tls.info] connecting: SSLv3/TLS write client hello
2021-03-11 16:03:58,628 mod_proxy/0.8[282494]: unable to connect using TLS: system call error: [2] No such file or directory
2021-03-11 16:03:58,628 mod_proxy/0.8[282494]: unable to open data connection to s-XXXX.server.transfer.ca-central-1.amazonaws.com: TLS negotiation failed
2021-03-11 16:03:58,628 mod_proxy/0.8[282494]: postopen error for backend data connection output stream: Operation not permitted

**Comment by Castaglia** [comment]
> 530 Access Denied
Silly AWS.  _Sigh_.

For some reason, I thought you were using `mod_proxy` as a _reverse_ proxy to AWS, but I noticed you have:
```
ProxyRole forward
```
Any particular reason you're using a forward proxy for this use case?

**Comment by kdesjard** [comment]
FEAT works after logging in.

230 User logged in, proceed.
FEAT
211-Extensions supported
 SIZE
 MDTM
 LANG en
 MLST Size;Modify;Type;Perm
 AUTH SSL
 AUTH TLS
 MODE Z
 UTF8
 TVFS
 EPSV
211 End

The use case involves connecting one or two legacy systems (machine2machine) to AWS, so forwarding made more sense to me.  I just tried reverse and had the same issue.

**Comment by Castaglia** [comment]
I'm re-running my regression tests -- and found that indeed `ProxyTLSTransferProtectionPolicy clear` is not working as intended.  I'll be working to fix this -- and hopefully, in doing it, it will allow successful interactions with AWS.

**Comment by Castaglia** [comment]
Looks like AWS is not fully compliant with RFC 4217 (FTP over TLS), particularly in its `FEAT` response; see [here](https://tools.ietf.org/html/rfc4217#section-6):
> If a server supports the FEAT command, then it MUST advertise supported AUTH, PBSZ, and PROT commands in the reply,

And we don't see `PROT` or `PBSZ` in their `FEAT` response.  That will make my job more difficult.

**Comment by Castaglia** [comment]
@kdesjard https://github.com/Castaglia/proftpd-mod_proxy/pull/195 should fix the handling of `ProxyTLSTransferProtectionPolicy`, so that it works as it should.  And that, in turn, might hopefully fix this interaction with AWS.  Care to try it out?

**Comment by kdesjard** [comment]
Still not working, so tried a manual login with openssl s_client and:

230 User logged in, proceed.
PROT C
200 Command PROT okay.
PASV
227 Entering Passive Mode (X,X,X,X,32,3)
LIST
521 Data connection cannot be opened with this PROT setting
PROT P
200 Command PROT okay.
PASV
227 Entering Passive Mode (X,X,X,X,32,2)
LIST
150 File status okay; about to open data connection.

So data protection is required after all.. Setting ProxyTLSTransferProtectionPolicy to required still doesn't work. 

Here is a debug output from lftp which may be useful:

---- Connecting to AWS (X.X.X.X) port 21
<--- 220 Service ready for new user.
---> FEAT
<--- 534 TLS required, configure with AUTH first.
---> AUTH TLS
<--- 234 Command AUTH okay; starting TLS connection.
---> USER test
Certificate:
 Issued by:
 Checking against:
  Trusted
Certificate:
 Issued by:
  Trusted
WARNING: Certificate verification: hostname checking disabled
<--- 331 User name okay, need password for test.
---> PASS XXXX
<--- 230 User logged in, proceed.
---> FEAT
<--- 211-Extensions supported
<---  SIZE
<---  MDTM
<---  LANG en
<---  MLST Size;Modify;Type;Perm
<---  AUTH SSL
<---  AUTH TLS
<---  MODE Z
<---  UTF8
<---  TVFS
<---  EPSV
<--- 211 End
---> PBSZ 0
<--- 200 Command PBSZ okay.
---> LANG
<--- 200 Command LANG okay.
---> OPTS UTF8 ON
<--- 200 Command OPTS okay.
---> OPTS MLST Size;Modify;Type;Perm
<--- 200 Command OPTS okay.
---> PROT P
<--- 200 Command PROT okay.
---> MODE Z
<--- 200 Command MODE okay.
---> PASV
<--- 227 Entering Passive Mode (X,X,X,X,32,6)
---- Connecting data socket to (X.X.X.X) port 8198
---- Data connection established
0:0 translated to pair 0:0 (0,0)
0 translated to pair 0:0 (0,0)
0:0 translated to pair 0:0 (0,0)
0 translated to pair 0:0 (0,0)
0:0 translated to pair 0:0 (0,0)
0 translated to pair 0:0 (0,0)

**Comment by Castaglia** [comment]
Thanks for trying out the patch.  I'll merge it, as it _does_ fix `ProxyTLSTransferProtectionPolicy` to work properly.  (Can you confirm, at least, that using a "clear" policy means that `mod_proxy` does not attempt to do a TLS connection for the data transfer -- even if that won't work with AWS?)

In the mean time, I'll work on a patch to have `mod_proxy` always send `PBSZ` and `PROT`, even if the server's `FEAT` response doesn't show them as supported.

**Comment by kdesjard** [comment]
Unfortunately, it did try TLS for the data transfer when set to clear.  I had done some debugging and saw that proxy_post_prot was not being called, however, I'm not familiar with the hierarchy of all the calls.

**Comment by Castaglia** [comment]
No worries, that helps.  The `proxy_post_prot` command handler, in `mod_proxy`, is only called if/when the frontend client sends a `PROT` command.  And since you mention that your frontend client is just doing FTP, not FTPS, then I would not expect that client to send the `PROT` command.  I'll add that configuration to my regression suite, and see what I can find.

**Comment by Castaglia** [comment]
@kdesjard when you get a chance, could you test out the latest version of that branch/PR?  I've updated it to handle the case where the frontend client is using plain FTP.  This means that, since AWS wants TLS for the data transfers, you can comment out your `ProxyTLSTransferProtectionPolicy` directive (default is "client", which uses TLS for data transfers), or you can set it explicitly to be:
```
ProxyTLSTransferProtectionPolicy required
```

**Comment by kdesjard** [comment]
Progress!  However, one transfer works, and the next crashes:

-----BEGIN STACK TRACE-----
[0] proftpd: user@aws - (connecting): STOR TESTFILE() [0x4c38ae]
[1] proftpd: user@aws - (connecting): STOR TESTFILE() [0x4c38ae]
[2] proftpd: user@aws - (connecting): STOR TESTFILE(pr_netio_write+0x27e) [0x44028e]
[3] proftpd: user@aws - (connecting): STOR TESTFILE(proxy_netio_write+0x45) [0x4bf995]
[4] proftpd: user@aws - (connecting): STOR TESTFILE(proxy_ftp_data_send+0x8e) [0x4d182e]
[5] proftpd: user@aws - (connecting): STOR TESTFILE() [0x4b9205]
[6] proftpd: user@aws - (connecting): STOR TESTFILE() [0x4badeb]
[7] proftpd: user@aws - (connecting): STOR TESTFILE(pr_module_call+0x44) [0x446314]
[8] proftpd: user@aws - (connecting): STOR TESTFILE() [0x41c32a]
[9] proftpd: user@aws - (connecting): STOR TESTFILE(pr_cmd_dispatch_phase+0x20c) [0x41e93c]
[10] proftpd: user@aws - (connecting): STOR TESTFILE() [0x4b3362]
[11] proftpd: user@aws - (connecting): STOR TESTFILE() [0x4b33b2]
[12] proftpd: user@aws - (connecting): STOR TESTFILE() [0x41d07a]
[13] proftpd: user@aws - (connecting): STOR TESTFILE() [0x41d905]
[14] proftpd: user@aws - (connecting): STOR TESTFILE(main+0x51a) [0x41bb7a]
[15] /lib64/libc.so.6(__libc_start_main+0xf3) [0x7fd4f7de07b3]
[16] proftpd: user@aws - (connecting): STOR TESTFILE(_start+0x2e) [0x41c02e]
-----END STACK TRACE-----
ProFTPD terminating (signal 11)

**Comment by Castaglia** [comment]
I finally found the cause of that segfault; twas an unexpected NULL pointer dereference, caused by a more subtle and lurking bug.  But the latest changes in that branch/PR now work as expected for me, if you'd care to try it out?

**Comment by kdesjard** [comment]
Unfortunately still crashing.

-----BEGIN STACK TRACE-----
[0] proftpd: test@aws - (connecting): STOR TESTFILE() [0x4c38ae]
[1] proftpd: test@aws - (connecting): STOR TESTFILE() [0x4c38ae]
[2] proftpd: test@aws - (connecting): STOR TESTFILE(pr_netio_write+0x27e) [0x44028e]
[3] proftpd: test@aws - (connecting): STOR TESTFILE(proxy_netio_write+0x45) [0x4bf995]
[4] proftpd: test@aws - (connecting): STOR TESTFILE(proxy_ftp_data_send+0x8e) [0x4d182e]
[5] proftpd: test@aws - (connecting): STOR TESTFILE() [0x4b9205]
[6] proftpd: test@aws - (connecting): STOR TESTFILE() [0x4badeb]
[7] proftpd: test@aws - (connecting): STOR TESTFILE(pr_module_call+0x44) [0x446314]
[8] proftpd: test@aws - (connecting): STOR TESTFILE() [0x41c32a]
[9] proftpd: test@aws - (connecting): STOR TESTFILE(pr_cmd_dispatch_phase+0x20c) [0x41e93c]
[10] proftpd: test@aws - (connecting): STOR TESTFILE() [0x4b3362]
[11] proftpd: test@aws - (connecting): STOR TESTFILE() [0x4b33b2]
[12] proftpd: test@aws - (connecting): STOR TESTFILE() [0x41d07a]
[13] proftpd: test@aws - (connecting): STOR TESTFILE() [0x41d905]
[14] proftpd: test@aws - (connecting): STOR TESTFILE(main+0x51a) [0x41bb7a]
[15] /lib64/libc.so.6(__libc_start_main+0xf3) [0x7f5bf67847b3]
[16] proftpd: test@aws - (connecting): STOR TESTFILE(_start+0x2e) [0x41c02e]
-----END STACK TRACE-----
ProFTPD terminating (signal 11)

**Comment by Castaglia** [comment]
@kdesjard Hmm, OK.  I'm not able to reproduce that segfault locally, so the next thing to try is to get more information from your build.  Can you do:
```
$ addr2line -e /usr/local/sbin/proftpd 0x4c38ae
$ addr2line -e /usr/local/sbin/proftpd 0x44028e
```
The `addr2line` command takes a memory address (the hex number) and the binary, and should hopefully provide a filename and line number, which can help track down the source/location of this segfault.

**Comment by kdesjard** [comment]
proftpd/contrib/mod_proxy/lib/proxy/tls.c:655
proftpd/src/netio.c:1153

**Comment by Castaglia** [comment]
Hmm.  Odd.  That's the segfault I'm pretty sure I fixed in https://github.com/Castaglia/proftpd-mod_proxy/commit/b63c95cca93d4c56f39031f60308448ed61440d2.  I'll merge that PR (it's a good change anyway), so you can just install/build the latest `mod_proxy` code from master, and we'll go from there.

**Comment by kdesjard** [comment]
Apologies, I copied the module into the module's directory by accident (mod_proxy/proftpd-mod_proxy).  

I can confirm it is working now.

Thank you for all your assistance.

**Comment by Castaglia** [comment]
Excellent news!  I'm glad to hear that `mod_proxy` is now working properly for your AWS Transfer Family needs.
